title: RyeoHwan
description: 안녕하세요 함께 성장하고 싶은 개발자 안려환입니다.
site_title: 'RyeoRyeo'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Ryeohwan
blog_url: https://www.nagekar.com
email: arh951019@gmail.com
keybase_username: Ryeohwan
twitter_username: Ryeohwan
reddit_username: Ryeohwan

# absolute or relative
profile_picture: assets/images/RyeoRyeo.jpg

# Google Analytics ID
google_analytics: 